### ISSUE TITLE
[Bug]: Semantic versioning syntax

### ISSUE THREAD

**Issue by simonbohnen** [Apodini/ApodiniDocumentExport#1]
### Description

Apodini currently doesn't build for me:
```
error: Dependencies could not be resolved because no versions of 'apodinidocumentexport' match the requirement 0.1.0..<0.2.0 and root depends on 'apodinidocumentexport' 0.1.0..<0.2.0.
```

I think this is because the syntax for semantic versioning does not use a 'v' in the beginning, and the version for ApodiniDocumentExport was tagged as 'v0.1.0'. Could you change that to '0.1.0' @valentinbootz?

### Reproduction

`swift build` in Apodini

### Expected behavior

Building normally.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by valentinbootz** [comment]
@simonbohnen Thank you Simon! I just created the new tag. Please check if it works now, thank you!

**Comment by simonbohnen** [comment]
Works, thx!
